name: Check Delta and Create PR

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  check_and_update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub
        
        
    - name: List contents of workspace directory
      run: ls -al ${{ github.workspace }}


    - name: Run the check and update script
      env:
        FILE_URL: ${{ secrets.FILE_URL }}
        REPO_DIR: ${{ github.workspace }}
        TARGET_DIR: 'test_dir'  # Replace with the directory you want to check within the repository
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        REPO_NAME: ${{ github.repository }}
      run: python scripts/check_delta_and_create_pr.py
